### ISSUE TITLE
ValueError: Gas estimation failed: 'execution reverted: VM Exception while processing transaction: revert'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

### ISSUE THREAD

**Issue by Provenance-Market** [Ed-Marcavage/NFT-#2]

**Comment by Ed-Marcavage** [comment]
You need to use the addresses from Chainlink VRF v1 NOT v2 in your .yaml, remember to re-deploy your contract with these newly updated addresses. Please see the link below for the addresses:

https://docs.chain.link/docs/vrf/v1/supported-networks/

https://stackoverflow.com/questions/71194882/execution-reverted-during-call-this-transaction-will-likely-revert-if-you-wish
